### ISSUE TITLE
Invalid callback PHPMailer\PHPMailer\SMTP::errorHandler, cannot access protected method PHPMailer\PHPMailer\SMTP::errorHandler()

### ISSUE THREAD

**Issue by nfangxu** [Yurunsoft/PHPMailer-Swoole#3]
phpmailer 版本是 6.1.5 出现异常 `Invalid callback PHPMailer\PHPMailer\SMTP::errorHandler, cannot access protected method PHPMailer\PHPMailer\SMTP::errorHandler()`

直接使用 `phpmailer` 是正常的

**Comment by Yurunsoft** [comment]
安装最新版Swoole，开启一键协程化，使用原版phpmailer就可以实现协程化了。本项目已经没有维护下去的意义。
一键协程化:<http://wiki.swoole.com/#/runtime>
